using UnityEngine;
using System.Collections;
using TUIO;

/**
 * Do not edit this file - instead see ExampleCustomMoving3DObjectActionsListener.cs
 * for an example on how to add custom code
 */
public class MovingAndRotating3DObjectActionListener : Object3DActionListener {
	public float scalePositionX = 1f;
	public float scalePositionY = 1f;
	public float scalePositionZ = 1f;
	
	public override void updateTuioObject(Tuio3DObject o){
		transform.localPosition = getMoveVector(o);
		transform.localRotation = getRotationQuaternion(o);
	}
	
	protected Vector3 getMoveVector(Tuio3DObject o){		
		//Debug.Log("Move "+o.getX()+", "+o.getY()+", "+o.getZ());
		return new Vector3(o.getX()*scalePositionX, o.getY()*scalePositionY, o.getZ()*scalePositionZ);
    }

	protected Quaternion getRotationQuaternion(Tuio3DObject o){
		Debug.Log("Rotate: "+o.getAngleDegreesX()+", "+o.getAngleDegreesY()+", "+o.getAngleDegreesZ());
        return Quaternion.Euler(o.getAngleDegreesX(), o.getAngleDegreesY(),o.getAngleDegreesZ());
    }
}
